---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: koti-deployment
spec:
 replicas: 1
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: koti-koti
 template:
  metadata:
   name: koti-kotipod
   labels:
     app: koti-koti	 
  spec: 
    containers:
    - name: koti-koti
      image: manifestimage:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
 name: koti-service
spec:
  type: NodePort
  selector:
   app: koti-koti
  ports:
   - port: 3000
     targetPort: 3000
...
