---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: koti-deployments
spec:
 replicas: 1
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: koti-kotis
 template:
  metadata:
   name: koti-kotipods
   labels:
     app: koti-kotis	 
  spec: 
    containers:
    - name: koti-kotis
      image: koteswarararaosairi/k8sma:v12
      imagePullPolicy: Always
      ports:
      - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
 name: koti-services
spec:
  type: NodePort
  selector:
   app: koti-kotis
  ports:
   - port: 3000
     targetPort: 3001
...
